version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.20
    commands:
      - echo "Starting installation..."
      - echo "Go version: $(go version)"
      - echo "GOPROXY: $GOPROXY"
      - echo "GOPRIVATE: $GOPRIVATE"
      - go mod tidy
      - go mod download
