version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.18 # Specify the Go version
    commands:
      - echo "Installing Go dependencies..."      
      - go mod tidy # Clean up dependencies
  pre_build:
    commands:
      - echo "Starting build..."
  build:
    commands:
      - echo "Building the Go project..."
      - go build -o main.go # Compile the main.go file
  post_build:
    commands:
      - echo "Running the Go project..."
      - ./main.go # Run the built binary

artifacts:
  files:
    - main.go
